### ISSUE TITLE
Text Input on Belly Screen

### ISSUE THREAD

**Issue by patricialvesoliveira** [mayacakmak/robotfrontend#10]
Can we build the option to input text on the Belly Screen? This will allow teens to input some thoughts (e.g., essential for the Yes / No micro-intervention).

**Comment by kaimihata** [comment]
Initial version pushed to the backend. Text area input can be added via the database by adding an entry called textInput to a screen with fields as shown below. Front end still needs to be updated to add a text area component normally.
![Screen Shot 2020-09-09 at 8 46 31 PM](https://user-images.githubusercontent.com/22643220/92679564-9a618d00-f2dd-11ea-875b-083a8479f889.png)
