### ISSUE TITLE
Renaming or Deleting the Default Button

### ISSUE THREAD

**Issue by tanya17365** [mayacakmak/robotfrontend#11]
The default button in the belly screen ("Continue") cannot be deleted or renamed when adding button inputs to the belly screen of the Web Robot.
![Screenshot (100)](https://user-images.githubusercontent.com/44595936/87537978-23cb5900-c6b9-11ea-82e8-67a7466db8a9.png)

**Comment by kaimihata** [comment]
Need to change `buttons.names` to `buttons.list` in the if block that handles deleting the button.
