### ISSUE TITLE
Checkbox Options Not Displaying on Belly Screen

### ISSUE THREAD

**Issue by tanya17365** [mayacakmak/robotfrontend#16]
The EmotionShame, EmotionFear, etc features that are supposed to show checkboxes show only the main text and none of the checkboxes or the options within them.
![No Checkboxes for Emotion Options](https://user-images.githubusercontent.com/44595936/87542513-ad325980-c6c0-11ea-8f30-de2e087fcaff.png)

**Comment by samesoul** [comment]
Created pull request in backend repository for this issue, don't know how to link issues across repo's
